### ISSUE TITLE
"404 - page not found" not triggered

### ISSUE THREAD

**Issue by konnisoelch** [lochmueller/language_detection#27]
Somehow my 404 configuration isn't working after installing the plugin.

Instead i get directed to the homepage with 307.

Here you can see my settings:
![image](https://user-images.githubusercontent.com/22169163/159268103-9073389c-13e7-4957-ad64-66fafaefb903.png)

![image](https://user-images.githubusercontent.com/22169163/159268194-bf9ca2d4-919c-4867-bd39-393b3f45df12.png)

**Comment by konnisoelch** [comment]
Yeah that seems to work, but it would be really nice if it worked on all pages.

**Comment by lochmueller** [comment]
Hmmm. Could you explain the use case for the "All pages". I suggest that I drop this function, because first, it is hard to handle and second, I think there is no use case. Because the user call a deeplink, because he found the page via a search Engine or click a link on another website. I both cases, I recommend no redirect for the user. A search engine search content in the right languages and if a foreign website link to your Website, they take also care of the right language I think. So I strongly recommend that language detection should only work on the entry page (home page).

Regards,
Tim

**Comment by konnisoelch** [comment]
My suggestion was to first check for 404 errors and run the language detection afterwards, but tbh i don't know if that is possible. The cases you described make perfect sense, so i think we can close this issue. Thank you for your time!
