### ISSUE TITLE
language_detection prevent redirects

### ISSUE THREAD

**Issue by armin-gardenanet** [lochmueller/language_detection#36]
Hello,

he actually had the problem, that the extension language_detection prevent redirects from beeing redirect. 
It only happens when the source_path contains only parameters, for example: ?pagid=XXX&lang=deu
These are old URLs which we had to keep. Is there any solution to made them work? Otherwide we had to move them to the .htaccess.

Versions:
- Typo3: 11.5.38
- language_detection: 3.0.1
- redirects (core extension): 11.5.38

**Comment by lochmueller** [comment]
Hey @armin-gardenanet ,

do you try to move the middleware a little bit down in the middleware stack? https://github.com/lochmueller/language_detection/blob/main/Configuration/RequestMiddlewares.php#L10 

Like set before to "typo3/cms-frontend/page-resolver" and after to "typo3/cms-frontend/static-route-resolver"? The language detection will be a little bit slower, because more "stuff" is executed in front of the language detection redirect. But this should only be a few ms.

Regards,
Tim

**Comment by armin-gardenanet** [comment]
Hi Tim,
thanks for your advice, now it works perfectly. Thank you for your suppport and your great extension!

Regards,
Armin

**Comment by armin-gardenanet** [comment]
Just for other guys, who also has this problem: 
for correct language detection, i had to move the middleware after typo3/cms-redirects/redirecthandler and keep it before typo3/cms-frontend/base-redirect-resolver

**Comment by lochmueller** [comment]
Hey @armin-gardenanet ,
why the middleware must behind `typo3/cms-redirects/redirecthandler`. That means, that you have redirects that are trigger on `/` or why there is a problem with the EXT:redirect extension?
Regards,
Tim

**Comment by armin-gardenanet** [comment]
@lochmueller yes exactly, we had some old redirects from a different CMS, thats the reason we need the redirect on / (for example /?page=home&lang=eng).
With the solution you recommended in october, the language redirect didn't fires anymore and i was always redirected to the default language.

My working configuration:

![Image](https://github.com/user-attachments/assets/6102134e-1e0c-47f6-be94-b775db57b865)
